### ISSUE TITLE
Blackscreen

### ISSUE THREAD

**Issue by JakobGlieder** [ree1261/pyvidplayer#3] opened 2022-05-25 01:17 UTC
I just get a Black Window when playing my file using the example. No errors, but the pygame vid is just black

**Comment by gresm** [comment] 2022-06-23 11:33
I think the most crucial thing is that this issue lacks any information that may be useful.
Please provide simplest version of code that causes this effect (or just code).
Also, please add information of what version of python,pygame,pyvidplayer,operating system and anything that may be connected with this issue.
Your problem also may not be caused by the issue in this library, but just from incorrect usage of it in your code.
At the moment I recommend closing this issue for now.

**Comment by gerro-abarabar** [comment] 2022-07-08 21:46
I think you forgot to put `pygame.display.update()`

**Comment by gresm** [comment] 2022-07-09 12:12
I recommend closing this issue for now.

**Closed as completed** 2022-07-09 15:10 UTC
